name: test

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install requirements
        run: pip3 install -r requirements.txt

      - name: Run Python unit tests
        run: python3 -u -m unittest tests/suite.py

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Publish html
        run: |
          git add report_testing && git commit -m ':lipstick: new report'
          git subtree push --prefix report_testing origin report_page

      - name: Résumé
        run: echo "### Exécution des tests (main) effectué avec succès ! :rocket:" >> $GITHUB_STEP_SUMMARY
